/* Module: courses.js — Module 03, Course Template Library (manual path only).
 * Per SRS_Management_Module_03_Course_Template_Library.md,
 * TDS_Slice_M5_Management_App_Rev7.md §1/§4.
 * Bulk CSV import (FR-5) and Lesson content-planning presets (FR-P1-P6) are
 * M8 scope — not built here. */

const Courses = (() => {
  const RESERVED = ['CHR', 'EVT', 'TPL'];

  // Drill-down view state — which Course/Lesson is currently open. Persists
  // across route changes within the page lifetime; no AC governs a reset.
  let viewCourseId = null;
  let viewLessonId = null;
  let editActivityId = null; // when set, the Lesson detail shows the Activity edit form

  function randomToken(len = 6) {
    const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
    const bytes = new Uint8Array(len);
    crypto.getRandomValues(bytes);
    let out = '';
    for (let i = 0; i < len; i++) out += chars[bytes[i] % chars.length];
    return out;
  }

  function pad2(n) {
    return String(n).padStart(2, '0'); // minimum width 2, not a ceiling — same rule as Tier IDs.
  }

  function slugify(name) {
    return name.replace(/[^a-zA-Z0-9]/g, '');
  }

  function isReserved(code) {
    return RESERVED.includes(code.toUpperCase());
  }

  function isAlphanumeric(code) {
    return /^[a-zA-Z0-9]+$/.test(code);
  }

  // ---- Course-level reads ----

  async function listCourseTemplates() {
    const all = await Storage.getAll('courses');
    return all.filter((c) => c.state === 'template');
  }

  async function courseCodeExists(code, excludeId) {
    const templates = await listCourseTemplates();
    const norm = code.toLocaleUpperCase();
    return templates.some((c) => c.id !== excludeId && c.courseCode.toLocaleUpperCase() === norm);
  }

  async function hasActivitiesBeneathCourse(courseId) {
    const lessons = await Storage.getAllByIndex('lessons', 'by_courseId', courseId);
    for (const lesson of lessons) {
      const activities = await Storage.getAllByIndex('activities', 'by_lessonId', lesson.id);
      if (activities.length > 0) return true;
    }
    return false;
  }

  async function hasActivitiesUnderLesson(lessonId) {
    const activities = await Storage.getAllByIndex('activities', 'by_lessonId', lessonId);
    return activities.length > 0;
  }

  async function lessonCodeExists(code, courseId, excludeId) {
    const lessons = await Storage.getAllByIndex('lessons', 'by_courseId', courseId);
    const norm = code.toLocaleUpperCase();
    return lessons.some((l) => l.id !== excludeId && l.lessonCode.toLocaleUpperCase() === norm);
  }

  // ---- Course (FR-1, FR-2) ----

  async function validateCourseCode(rawCode, name, excludeId) {
    let code = rawCode && rawCode.trim();
    let autoGenerated = false;
    if (!code) {
      code = slugify(name);
      autoGenerated = true;
    }
    if (!code) return { error: 'Course code is required.' };
    if (!isAlphanumeric(code)) return { error: 'Course code must be alphanumeric only.' };
    if (isReserved(code)) return { error: `Course code may not be "${code.toUpperCase()}" (reserved).` };
    if (await courseCodeExists(code, excludeId)) {
      return {
        error: autoGenerated
          ? `Auto-generated code "${code}" already exists — please enter one manually.`
          : 'A Course with this code already exists.',
      };
    }
    return { code };
  }

  function buildCourseRecord(id, fields, courseCode) {
    const record = {
      id,
      name: fields.name.trim(),
      curriculumId: fields.curriculumId,
      courseCode,
      mainCategory: 'school',
      state: 'template',
    };
    if (fields.coreElective) record.coreElective = fields.coreElective;
    if (fields.subject) record.subject = fields.subject.trim();
    if (fields.description) record.description = fields.description.trim();
    if (fields.defaultPacingHint) record.defaultPacingHint = fields.defaultPacingHint.trim();
    return record;
  }

  async function createCourse(fields) {
    if (!fields.name || !fields.name.trim()) return { error: 'Name is required.' };
    if (!fields.curriculumId) return { error: 'A Curriculum must be selected.' };

    const codeResult = await validateCourseCode(fields.courseCode, fields.name, undefined);
    if (codeResult.error) return { error: codeResult.error };

    const record = buildCourseRecord('COU-' + randomToken(), fields, codeResult.code);
    await Storage.put('courses', record);
    return { record };
  }

  async function editCourse(id, fields) {
    const existing = await Storage.get('courses', id);
    if (!fields.name || !fields.name.trim()) return { error: 'Name is required.' };

    let courseCode = existing.courseCode;
    const requestedCode = fields.courseCode && fields.courseCode.trim();
    if (requestedCode && requestedCode.toLocaleUpperCase() !== existing.courseCode.toLocaleUpperCase()) {
      if (await hasActivitiesBeneathCourse(id)) {
        return { error: 'Course code is frozen: at least one Activity exists beneath this Course.' };
      }
      const codeResult = await validateCourseCode(requestedCode, fields.name, id);
      if (codeResult.error) return { error: codeResult.error };
      courseCode = codeResult.code;
    }

    // Preserve every field the edit form doesn't manage (curriculumId,
    // subject, description, coreElective, defaultPacingHint) — only name
    // and courseCode are ever overwritten here.
    const record = { ...existing, name: fields.name.trim(), courseCode };
    await Storage.put('courses', record);
    return { record };
  }

  // Unguarded (Module 03 §2.4) — cascades to this template's own Lessons and
  // Activities. Never touches any Child Course Instance (independent copy).
  async function deleteCourse(id) {
    const lessons = await Storage.getAllByIndex('lessons', 'by_courseId', id);
    await Storage.runTransaction(['courses', 'lessons', 'activities'], 'readwrite', (t) => {
      const activitiesStore = t.objectStore('activities');
      for (const lesson of lessons) {
        const req = activitiesStore.index('by_lessonId').getAllKeys(lesson.id);
        req.onsuccess = () => {
          for (const key of req.result) activitiesStore.delete(key);
        };
      }
      const lessonsStore = t.objectStore('lessons');
      for (const lesson of lessons) lessonsStore.delete(lesson.id);
      t.objectStore('courses').delete(id);
    });
    return { blocked: false };
  }

  // ---- Lesson (FR-3) ----

  function buildLessonRecord(id, courseId, fields, lessonCode, nextActivitySeq) {
    const record = {
      id,
      courseId,
      lessonCode,
      order: Number(fields.order),
      title: fields.title.trim(),
      nextActivitySeq,
    };
    if (fields.objective) record.objective = fields.objective.trim();
    if (fields.estimatedDays !== undefined && fields.estimatedDays !== '') {
      record.estimatedDays = Number(fields.estimatedDays);
    }
    return record;
  }

  async function validateLessonCode(rawCode, order, courseId, excludeId) {
    let code = rawCode && rawCode.trim();
    if (!code) code = 'L' + pad2(Number(order) + 1);
    if (!isAlphanumeric(code)) return { error: 'Lesson code must be alphanumeric only.' };
    if (isReserved(code)) return { error: `Lesson code may not be "${code.toUpperCase()}" (reserved).` };
    if (await lessonCodeExists(code, courseId, excludeId)) {
      return { error: 'A Lesson with this code already exists in this Course.' };
    }
    return { code };
  }

  async function createLesson(courseId, fields) {
    if (!fields.title || !fields.title.trim()) return { error: 'Title is required.' };
    if (fields.order === undefined || fields.order === '') return { error: 'Order is required.' };

    const codeResult = await validateLessonCode(fields.lessonCode, fields.order, courseId, undefined);
    if (codeResult.error) return { error: codeResult.error };

    const record = buildLessonRecord('LSN-' + randomToken(), courseId, fields, codeResult.code, 1);
    await Storage.put('lessons', record);
    return { record };
  }

  async function editLesson(id, fields) {
    const existing = await Storage.get('lessons', id);
    if (!fields.title || !fields.title.trim()) return { error: 'Title is required.' };

    let lessonCode = existing.lessonCode;
    const requestedCode = fields.lessonCode && fields.lessonCode.trim();
    if (requestedCode && requestedCode.toLocaleUpperCase() !== existing.lessonCode.toLocaleUpperCase()) {
      if (await hasActivitiesUnderLesson(id)) {
        return { error: 'Lesson code is frozen: at least one Activity exists under this Lesson.' };
      }
      const codeResult = await validateLessonCode(requestedCode, fields.order, existing.courseId, id);
      if (codeResult.error) return { error: codeResult.error };
      lessonCode = codeResult.code;
    }

    const record = buildLessonRecord(id, existing.courseId, fields, lessonCode, existing.nextActivitySeq);
    await Storage.put('lessons', record);
    return { record };
  }

  // Cascades to this Lesson's own Activities (composition). Never touches
  // any stamped Child Course Instance.
  async function deleteLesson(id) {
    await Storage.runTransaction(['lessons', 'activities'], 'readwrite', (t) => {
      const activitiesStore = t.objectStore('activities');
      const req = activitiesStore.index('by_lessonId').getAllKeys(id);
      req.onsuccess = () => {
        for (const key of req.result) activitiesStore.delete(key);
      };
      t.objectStore('lessons').delete(id);
    });
  }

  // ---- Activity (FR-4, FR-9) ----

  // Optional Activity fields (SRS Module 03 §4). All three are absent-when-blank:
  // a blank entry stores no property at all — never "", 0, null, or a default.
  const BLOCK_HINTS = ['morning', 'afternoon', 'evening', 'night']; // Interchange Contract §1d.

  // Reads only the optional keys the form actually submitted. A submitted-but-
  // blank value normalizes to null, meaning "omit on create / delete on edit".
  // Returns { error } on invalid input, else { fields: { <present keys> } }.
  function normalizeOptionalActivityFields(input) {
    const out = {};
    if ('expectedDurationMin' in input) {
      const raw = input.expectedDurationMin;
      if (raw === undefined || raw === null || String(raw).trim() === '') {
        out.expectedDurationMin = null;
      } else {
        const n = Number(raw);
        // Positive integer only. The 15-min fallback is generation-time math
        // (Module 05 §2.3), never persisted — so 0 is not a valid stored value.
        if (!Number.isInteger(n) || n < 1) {
          return { error: 'Expected duration (min) must be a positive whole number, or left blank.' };
        }
        out.expectedDurationMin = n;
      }
    }
    if ('instructions' in input) {
      const raw = input.instructions;
      out.instructions =
        raw === undefined || raw === null || String(raw).trim() === '' ? null : String(raw).trim();
    }
    if ('blockHint' in input) {
      const raw = input.blockHint;
      if (!raw) out.blockHint = null;
      else if (!BLOCK_HINTS.includes(raw)) return { error: 'Block hint must be morning, afternoon, evening, or night.' };
      else out.blockHint = raw;
    }
    return { fields: out };
  }

  // Set when a value is present, delete when null. Never touches any other field.
  function applyOptionalActivityFields(record, normalized) {
    for (const key of ['expectedDurationMin', 'instructions', 'blockHint']) {
      if (key in normalized) {
        if (normalized[key] === null) delete record[key];
        else record[key] = normalized[key];
      }
    }
  }

  function blockHintOptions(selected) {
    return ['', ...BLOCK_HINTS]
      .map((v) => {
        const label = v === '' ? '(none)' : v;
        const sel = v === (selected || '') ? ' selected' : '';
        return `<option value="${v}"${sel}>${label}</option>`;
      })
      .join('');
  }

  function isCustomType(type) {
    return type.activityTypeKey.startsWith('AT-');
  }

  function buildPayload(type, form) {
    if (!isCustomType(type) && type.structurePattern === 'page-range') {
      const start = Number(form.pageRangeStart.value);
      const end = Number(form.pageRangeEnd.value);
      if (!form.pageRangeStart.value || !form.pageRangeEnd.value) {
        return { error: 'Page range start and end are required.' };
      }
      if (start > end) return { error: 'Page range start must not exceed end.' };
      return { payload: { pageRangeStart: start, pageRangeEnd: end } };
    }
    if (!isCustomType(type) && type.activityTypeKey === 'practice-level') {
      return { payload: {} }; // sequenceNumber IS the payload (§8) — no separate field.
    }
    if (!isCustomType(type)) {
      // Selector reference for platform-hosted count types (Video, Quiz, etc.).
      if (!form.reference.value.trim()) return { error: 'Reference is required.' };
      return { payload: { reference: form.reference.value.trim() } };
    }
    // Custom type — always a single free-text field, regardless of structurePattern (§8).
    // Stored as `{ text }` so Packet Generation's freeText projection (Interchange
    // Contract §1a payload; TDS_Slice_M7 §4.5) reads it directly — no rename at emit.
    if (!form.referenceOrInstructions.value.trim()) return { error: 'This field is required.' };
    return { payload: { text: form.referenceOrInstructions.value.trim() } };
  }

  async function createActivity(lessonId, fields, type, tier) {
    if (!fields.title || !fields.title.trim()) return { error: 'Title is required.' };
    if (!tier) return { error: 'Difficulty Tier must resolve to an existing Tier.' };
    if (!type) return { error: 'Activity Type must resolve to an existing type.' };

    let sequenceNumber;
    if (type.structurePattern === 'count') {
      if (fields.sequenceNumber === undefined || fields.sequenceNumber === '') {
        return { error: 'Sequence number is required for this Activity Type.' };
      }
      sequenceNumber = Number(fields.sequenceNumber);
    }

    const optNorm = normalizeOptionalActivityFields(fields);
    if (optNorm.error) return { error: optNorm.error };

    const course = await Storage.get('courses', (await Storage.get('lessons', lessonId)).courseId);
    const lessonBefore = await Storage.get('lessons', lessonId);
    const existingActivities = await Storage.getAllByIndex('activities', 'by_lessonId', lessonId);
    const order = existingActivities.length
      ? Math.max(...existingActivities.map((a) => a.order)) + 1
      : 0;

    let mintedId;
    await Storage.runTransaction(['lessons', 'activities'], 'readwrite', (t) => {
      const lessonsStore = t.objectStore('lessons');
      const getReq = lessonsStore.get(lessonId);
      getReq.onsuccess = () => {
        const lesson = getReq.result;
        const seq = lesson.nextActivitySeq;
        mintedId = `${course.courseCode}-TPL-${lesson.lessonCode}-${pad2(seq)}`;

        const record = {
          id: mintedId,
          lessonId,
          activityType: type.activityTypeKey,
          title: fields.title.trim(),
          required: !!fields.required,
          payload: fields.payload,
          difficultyTier: tier.tierId,
          capturesGrade: type.capturePattern === 'grade-optional',
          order,
          lessonTitle: lessonBefore.title,
        };
        if (sequenceNumber !== undefined) record.sequenceNumber = sequenceNumber;
        applyOptionalActivityFields(record, optNorm.fields);

        t.objectStore('activities').put(record);
        lessonsStore.put({ ...lesson, nextActivitySeq: seq + 1 });
      };
    });

    return { id: mintedId };
  }

  async function editActivity(id, fields, tier) {
    const existing = await Storage.get('activities', id);
    if (!fields.title || !fields.title.trim()) return { error: 'Title is required.' };
    if (!tier) return { error: 'Difficulty Tier must resolve to an existing Tier.' };

    const optNorm = normalizeOptionalActivityFields(fields);
    if (optNorm.error) return { error: optNorm.error };

    // Spread preserves id/seq/order/lessonId/payload/capturesGrade/lessonTitle —
    // editing never re-mints the id and never touches seq, order, or sequenceNumber
    // (sequenceNumber only changes when the form explicitly submits a new value).
    const record = {
      ...existing,
      title: fields.title.trim(),
      required: !!fields.required,
      difficultyTier: tier.tierId,
    };
    if (fields.payload) record.payload = fields.payload;
    if (fields.sequenceNumber !== undefined && fields.sequenceNumber !== '') {
      record.sequenceNumber = Number(fields.sequenceNumber);
    }
    applyOptionalActivityFields(record, optNorm.fields);
    await Storage.put('activities', record);
    return { record };
  }

  async function deleteActivity(id) {
    await Storage.del('activities', id);
  }

  // FR-9 — swaps `order` between adjacent Activities in the same Lesson only.
  async function moveActivity(lessonId, activityId, direction) {
    const activities = (await Storage.getAllByIndex('activities', 'by_lessonId', lessonId)).sort(
      (a, b) => a.order - b.order
    );
    const idx = activities.findIndex((a) => a.id === activityId);
    const swapIdx = direction === 'up' ? idx - 1 : idx + 1;
    if (idx === -1 || swapIdx < 0 || swapIdx >= activities.length) return;

    const a = activities[idx];
    const b = activities[swapIdx];
    await Storage.runTransaction(['activities'], 'readwrite', (t) => {
      const store = t.objectStore('activities');
      store.put({ ...a, order: b.order });
      store.put({ ...b, order: a.order });
    });
  }

  // ---- Rendering ----

  function escapeHtml(str) {
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
  }

  async function render(root) {
    if (viewLessonId) return renderLessonDetail(root);
    if (viewCourseId) return renderCourseDetail(root);
    return renderCourseList(root);
  }

  async function renderCourseList(root) {
    root.innerHTML = '';
    const [courses, curricula] = await Promise.all([listCourseTemplates(), Storage.getAll('curricula')]);

    const heading = document.createElement('h1');
    heading.textContent = 'Course Template Library';
    root.appendChild(heading);

    const list = document.createElement('ul');
    list.className = 'course-list';
    courses.forEach((c) => {
      const item = document.createElement('li');
      item.innerHTML = `
        <span class="course-name">${escapeHtml(c.name)}</span>
        <span class="course-code">${escapeHtml(c.courseCode)}</span>
        <button data-action="open">Open</button>
        <button data-action="delete">Delete</button>
      `;
      item.querySelector('[data-action="open"]').addEventListener('click', () => {
        viewCourseId = c.id;
        render(root);
      });
      item.querySelector('[data-action="delete"]').addEventListener('click', async () => {
        await deleteCourse(c.id);
        render(root);
      });
      list.appendChild(item);
    });
    root.appendChild(list);

    const form = document.createElement('form');
    const curriculumOptions = curricula.map((c) => `<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('');
    form.innerHTML = `
      <h2>Add Course</h2>
      <label>Name<input type="text" name="name" required></label>
      <label>Curriculum<select name="curriculumId"><option value="">(select)</option>${curriculumOptions}</select></label>
      <label>Course code (blank = auto)<input type="text" name="courseCode"></label>
      <p class="error" hidden></p>
      <button type="submit">Add Course</button>
    `;
    const errorEl = form.querySelector('.error');
    form.addEventListener('submit', async (e) => {
      e.preventDefault();
      const result = await createCourse({
        name: form.name.value,
        curriculumId: form.curriculumId.value,
        courseCode: form.courseCode.value,
      });
      if (result.error) {
        errorEl.hidden = false;
        errorEl.textContent = result.error;
        return;
      }
      render(root);
    });
    root.appendChild(form);
  }

  async function renderCourseDetail(root) {
    root.innerHTML = '';
    const course = await Storage.get('courses', viewCourseId);
    if (!course) {
      viewCourseId = null;
      return render(root);
    }
    const frozen = await hasActivitiesBeneathCourse(course.id);
    const lessons = (await Storage.getAllByIndex('lessons', 'by_courseId', course.id)).sort(
      (a, b) => a.order - b.order
    );

    const backBtn = document.createElement('button');
    backBtn.textContent = '← Back to Courses';
    backBtn.addEventListener('click', () => {
      viewCourseId = null;
      render(root);
    });
    root.appendChild(backBtn);

    const heading = document.createElement('h1');
    heading.textContent = course.name;
    root.appendChild(heading);

    const editForm = document.createElement('form');
    editForm.innerHTML = `
      <h2>Edit Course</h2>
      <label>Name<input type="text" name="name" value="${escapeHtml(course.name)}" required></label>
      <label>Course code${frozen ? ' (frozen — Activities exist beneath this Course)' : ''}
        <input type="text" name="courseCode" value="${escapeHtml(course.courseCode)}" ${frozen ? 'disabled' : ''}>
      </label>
      <p class="error" hidden></p>
      <p class="success" hidden></p>
      <button type="submit">Save</button>
    `;
    const editErr = editForm.querySelector('.error');
    const editOk = editForm.querySelector('.success');
    editForm.addEventListener('submit', async (e) => {
      e.preventDefault();
      const result = await editCourse(course.id, {
        name: editForm.name.value,
        courseCode: frozen ? course.courseCode : editForm.courseCode.value,
      });
      if (result.error) {
        editErr.hidden = false;
        editErr.textContent = result.error;
        editOk.hidden = true;
        return;
      }
      editErr.hidden = true;
      editOk.hidden = false;
      editOk.textContent = 'Saved.';
      render(root);
    });
    root.appendChild(editForm);

    const lessonHeading = document.createElement('h2');
    lessonHeading.textContent = 'Lessons';
    root.appendChild(lessonHeading);

    const list = document.createElement('ul');
    list.className = 'lesson-list';
    lessons.forEach((l) => {
      const item = document.createElement('li');
      item.innerHTML = `
        <span class="lesson-title">${escapeHtml(l.title)}</span>
        <span class="lesson-code">${escapeHtml(l.lessonCode)}</span>
        <button data-action="open">Open</button>
        <button data-action="delete">Delete</button>
      `;
      item.querySelector('[data-action="open"]').addEventListener('click', () => {
        viewLessonId = l.id;
        render(root);
      });
      item.querySelector('[data-action="delete"]').addEventListener('click', async () => {
        await deleteLesson(l.id);
        render(root);
      });
      list.appendChild(item);
    });
    root.appendChild(list);

    const form = document.createElement('form');
    form.innerHTML = `
      <h3>Add Lesson</h3>
      <label>Title<input type="text" name="title" required></label>
      <label>Order<input type="number" name="order" value="${lessons.length}" required></label>
      <label>Lesson code (blank = auto)<input type="text" name="lessonCode"></label>
      <p class="error" hidden></p>
      <button type="submit">Add Lesson</button>
    `;
    const errorEl = form.querySelector('.error');
    form.addEventListener('submit', async (e) => {
      e.preventDefault();
      const result = await createLesson(course.id, {
        title: form.title.value,
        order: form.order.value,
        lessonCode: form.lessonCode.value,
      });
      if (result.error) {
        errorEl.hidden = false;
        errorEl.textContent = result.error;
        return;
      }
      render(root);
    });
    root.appendChild(form);
  }

  async function renderLessonDetail(root) {
    root.innerHTML = '';
    const lesson = await Storage.get('lessons', viewLessonId);
    if (!lesson) {
      viewLessonId = null;
      return render(root);
    }
    const [activityTypes, tiers] = await Promise.all([Storage.getAll('activityTypes'), Tiers.listSorted()]);
    const activities = (await Storage.getAllByIndex('activities', 'by_lessonId', lesson.id)).sort(
      (a, b) => a.order - b.order
    );

    const backBtn = document.createElement('button');
    backBtn.textContent = '← Back to Course';
    backBtn.addEventListener('click', () => {
      viewLessonId = null;
      render(root);
    });
    root.appendChild(backBtn);

    const heading = document.createElement('h1');
    heading.textContent = lesson.title;
    root.appendChild(heading);

    if (editActivityId) {
      const activity = activities.find((a) => a.id === editActivityId);
      if (!activity) {
        editActivityId = null;
      } else {
        root.appendChild(buildActivityEditForm(root, lesson, activity, activityTypes, tiers));
        return;
      }
    }

    const list = document.createElement('ul');
    list.className = 'activity-list';
    activities.forEach((a, index) => {
      const typeLabel = (activityTypes.find((t) => t.activityTypeKey === a.activityType) || {}).label || a.activityType;
      const item = document.createElement('li');
      item.innerHTML = `
        <span class="activity-title">${escapeHtml(a.title)}</span>
        <span class="activity-type">${escapeHtml(typeLabel)}</span>
        <span class="activity-id">${a.id}</span>
        <button data-action="up" ${index === 0 ? 'disabled' : ''}>&uarr;</button>
        <button data-action="down" ${index === activities.length - 1 ? 'disabled' : ''}>&darr;</button>
        <button data-action="edit">Edit</button>
        <button data-action="delete">Delete</button>
      `;
      item.querySelector('[data-action="up"]').addEventListener('click', async () => {
        await moveActivity(lesson.id, a.id, 'up');
        render(root);
      });
      item.querySelector('[data-action="down"]').addEventListener('click', async () => {
        await moveActivity(lesson.id, a.id, 'down');
        render(root);
      });
      item.querySelector('[data-action="edit"]').addEventListener('click', () => {
        editActivityId = a.id;
        render(root);
      });
      item.querySelector('[data-action="delete"]').addEventListener('click', async () => {
        await deleteActivity(a.id);
        render(root);
      });
      list.appendChild(item);
    });
    root.appendChild(list);

    root.appendChild(buildActivityForm(root, lesson, activityTypes, tiers));
  }

  function buildActivityForm(root, lesson, activityTypes, tiers) {
    const form = document.createElement('form');
    const typeOptions = activityTypes
      .map((t) => `<option value="${t.activityTypeKey}">${escapeHtml(t.label)}</option>`)
      .join('');
    const tierOptions = tiers.map((t) => `<option value="${t.tierId}">${escapeHtml(t.label)}</option>`).join('');

    form.innerHTML = `
      <h3>Add Activity</h3>
      <label>Activity Type<select name="activityType"><option value="">(select)</option>${typeOptions}</select></label>
      <label>Title<input type="text" name="title" required></label>
      <label>Required<input type="checkbox" name="required"></label>
      <label>Difficulty Tier<select name="difficultyTier"><option value="">(select)</option>${tierOptions}</select></label>
      <div class="payload-fields"></div>
      <label>Expected duration (min)<input type="number" name="expectedDurationMin" min="1" step="1"></label>
      <label>Instructions<input type="text" name="instructions"></label>
      <label>Block hint<select name="blockHint">${blockHintOptions('')}</select></label>
      <p class="error" hidden></p>
      <button type="submit">Add Activity</button>
    `;

    const payloadContainer = form.querySelector('.payload-fields');
    const errorEl = form.querySelector('.error');

    function renderPayloadFields() {
      const type = activityTypes.find((t) => t.activityTypeKey === form.activityType.value);
      if (!type) {
        payloadContainer.innerHTML = '';
        return;
      }
      const custom = isCustomType(type);
      let html = '';
      if (!custom && type.structurePattern === 'page-range') {
        html += `
          <label>Page range start<input type="number" name="pageRangeStart"></label>
          <label>Page range end<input type="number" name="pageRangeEnd"></label>
        `;
      } else if (!custom && type.activityTypeKey === 'practice-level') {
        html += '';
      } else if (!custom) {
        html += `<label>Reference<input type="text" name="reference"></label>`;
      } else {
        html += `<label>Reference / instructions<input type="text" name="referenceOrInstructions"></label>`;
      }
      if (type.structurePattern === 'count') {
        html += `<label>Sequence number<input type="number" name="sequenceNumber"></label>`;
      }
      payloadContainer.innerHTML = html;
    }

    form.activityType.addEventListener('change', renderPayloadFields);

    form.addEventListener('submit', async (e) => {
      e.preventDefault();
      const type = activityTypes.find((t) => t.activityTypeKey === form.activityType.value);
      const tier = tiers.find((t) => t.tierId === form.difficultyTier.value);
      if (!type) {
        errorEl.hidden = false;
        errorEl.textContent = 'Activity Type must resolve to an existing type.';
        return;
      }
      if (!tier) {
        errorEl.hidden = false;
        errorEl.textContent = 'Difficulty Tier must resolve to an existing Tier.';
        return;
      }
      const payloadResult = buildPayload(type, form);
      if (payloadResult.error) {
        errorEl.hidden = false;
        errorEl.textContent = payloadResult.error;
        return;
      }
      const result = await createActivity(
        lesson.id,
        {
          title: form.title.value,
          required: form.required.checked,
          payload: payloadResult.payload,
          sequenceNumber: type.structurePattern === 'count' ? form.sequenceNumber.value : undefined,
          expectedDurationMin: form.expectedDurationMin.value,
          instructions: form.instructions.value,
          blockHint: form.blockHint.value,
        },
        type,
        tier
      );
      if (result.error) {
        errorEl.hidden = false;
        errorEl.textContent = result.error;
        return;
      }
      render(root);
    });

    return form;
  }

  // Edit form for an existing Activity. Edits title, required, difficulty tier,
  // sequenceNumber (count types only), and the optional trio. Payload is left
  // untouched here (never re-minted, never re-validated) — same as the prior
  // rename flow. Saving never re-mints id and never touches seq/order.
  function buildActivityEditForm(root, lesson, activity, activityTypes, tiers) {
    const type = activityTypes.find((t) => t.activityTypeKey === activity.activityType);
    const isCount = type && type.structurePattern === 'count';
    const tierOptions = tiers
      .map(
        (t) =>
          `<option value="${t.tierId}"${t.tierId === activity.difficultyTier ? ' selected' : ''}>${escapeHtml(t.label)}</option>`
      )
      .join('');

    const form = document.createElement('form');
    form.innerHTML = `
      <h3>Edit Activity <code>${escapeHtml(activity.id)}</code></h3>
      <label>Title<input type="text" name="title" value="${escapeHtml(activity.title)}" required></label>
      <label>Required<input type="checkbox" name="required" ${activity.required ? 'checked' : ''}></label>
      <label>Difficulty Tier<select name="difficultyTier"><option value="">(select)</option>${tierOptions}</select></label>
      ${isCount ? `<label>Sequence number<input type="number" name="sequenceNumber" value="${activity.sequenceNumber ?? ''}"></label>` : ''}
      <label>Expected duration (min)<input type="number" name="expectedDurationMin" min="1" step="1" value="${activity.expectedDurationMin ?? ''}"></label>
      <label>Instructions<input type="text" name="instructions" value="${escapeHtml(activity.instructions || '')}"></label>
      <label>Block hint<select name="blockHint">${blockHintOptions(activity.blockHint)}</select></label>
      <p class="error" hidden></p>
      <button type="submit">Save</button>
      <button type="button" data-action="cancel">Cancel</button>
    `;
    const errorEl = form.querySelector('.error');

    form.querySelector('[data-action="cancel"]').addEventListener('click', () => {
      editActivityId = null;
      render(root);
    });

    form.addEventListener('submit', async (e) => {
      e.preventDefault();
      const tier = tiers.find((t) => t.tierId === form.difficultyTier.value);
      const result = await editActivity(
        activity.id,
        {
          title: form.title.value,
          required: form.required.checked,
          sequenceNumber: isCount ? form.sequenceNumber.value : undefined,
          expectedDurationMin: form.expectedDurationMin.value,
          instructions: form.instructions.value,
          blockHint: form.blockHint.value,
        },
        tier
      );
      if (result.error) {
        errorEl.hidden = false;
        errorEl.textContent = result.error;
        return;
      }
      editActivityId = null;
      render(root);
    });

    return form;
  }

  return {
    render,
    createCourse,
    editCourse,
    deleteCourse,
    createLesson,
    editLesson,
    deleteLesson,
    createActivity,
    editActivity,
    deleteActivity,
    moveActivity,
    listCourseTemplates,
    hasActivitiesBeneathCourse,
    hasActivitiesUnderLesson,
    lessonCodeExists,
    isReserved,
    isAlphanumeric,
  };
})();
